#!/usr/bin/perl -w

use PerlLib::SwissArmyKnife;
use String::ShellQuote;

foreach my $arg (@ARGV) {
  push @items, shell_quote($arg);
}
my $c = join(' ',@items);
# print "($c &)\n";
system "nohup $c > /dev/null 2>&1 &";
